project:
  status:
    doing: "Doing"
    completed: "Completed"
  num_per_page: 30
team:
  teams_number_per_page: 10
  basic: "basic"
  members: "members"
action:
  login: "login"
  logout: "logout"
user:
  users_number_per_page: 10
activity:
  personal: "personal"
  all: "all"
counter: 1
